### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by bbrendon** [Grayda/rocket-chat-lunch-club#2]
how do you install this?

**Comment by Grayda** [comment]
It's been a while since I used Rocket.Chat, but you should be able to create a new [outgoing webhook integration](https://rocket.chat/docs/administrator-guides/integrations/#outgoing-script-details) and paste in the Javascript contained in this repo, modifying the items in the array at the top to suit the type of foods you want available to pick.

**Comment by kyprio** [comment]
Hi, this little application is great ! I've just installed it for the RocketChat of my school.
But I also had to spend some time for integrating it correctly. Could you just add the following step by step instruction on the README.md so that we all be able to integrate it faster. Thank you very much for your plugin  !
For the current version of RocketChat 0.74.2, these is how is we can integrate Rocket-chat-lunch-club in the #general channel : 
Options > Administration > Integration > New Integration > Outgoing WebHook
Event Trigger : Message Sent
Enabled : True
Channel : #general
URLs : http://not_important_url.com
Script Enabled : True
Script : (content of the rocket-chat-lunch-club.js modified at you convenience)
Save Changes

**Comment by Grayda** [comment]
Thanks for the step-by-step. I've updated the README in d84d390c4c37b13bfb7d03cb741a42553491fd96 to include those steps. 

I might have to suggest Rocket.chat again at work, see if there's renewed interest in it..
